//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Booking_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int AdmID { get; set; }
        public int AdmLoginID { get; set; }
        public Nullable<int> CustID { get; set; }
    
        public virtual AdminLogin AdminLogin { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
