//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Booking_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public int BusID { get; set; }
        public string BusName { get; set; }
        public string BusNumber { get; set; }
        public Nullable<short> BusStatus { get; set; }
        public Nullable<int> BusSeat { get; set; }
    }
}
