//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Booking_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Admins = new HashSet<Admin>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int CustID { get; set; }
        public string CustName { get; set; }
        public string CustGender { get; set; }
        public string CustContact { get; set; }
        public string CustCnic { get; set; }
        public string CustDeparture { get; set; }
        public string CustArrival { get; set; }
        public System.DateTime CustDate { get; set; }
        public string CustBus { get; set; }
        public int CustPrice { get; set; }
        public byte[] CustImage { get; set; }
        public Nullable<int> CustLoginID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin> Admins { get; set; }
        public virtual CustomerLogin CustomerLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
