//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Booking_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int RegID { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string City { get; set; }
        public string Contact { get; set; }
        public string Cnic { get; set; }
        public string Password { get; set; }
        public byte[] Image { get; set; }
    }
}
